# This is a basic workflow to help you get started with Actions

name: exampleName

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#Начало секции первой джобы
  print_hello:
    #Среда выполнения
    runs-on: ubuntu-latest 
    #Начало секции шагов
    steps:
        # Название шага
      - name: hello
       #Команда, которая будет выполнена в терминале
        run: echo "Hello GitHub Actions!"
